### ISSUE TITLE
Class not found error when current directory has vendor directory

### ISSUE THREAD

**Issue by berarma** [wsdl2phpgenerator/wsdl2phpgenerator-cli#4]
When trying to run the cli inside a composer's project directory I get an error:

> PHP Fatal error:  Class 'Wsdl2PhpGenerator\Console\Application' not found in phar:///usr/local/bin/wsdl2phpgenerator-2.4.0.phar/wsdl2php.php on line 11
> PHP Stack trace:
> PHP   1. {main}() /usr/local/bin/wsdl2phpgenerator-2.4.0.phar:0
> PHP   2. require() /usr/local/bin/wsdl2phpgenerator-2.4.0.phar:10

Renaming the vendor directory fixes the problem so I guess it's trying to load the classes from there instead of looking in the phar file.

**Comment by kasperg** [comment]
Have you tried using a more recent release?

Your output refers to 2.4.0 and the latest release distributed as a phar files is [2.5.5](https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/releases/tag/2.5.5).

**Comment by berarma** [comment]
Yes, that one works. But why this project exists if the latest cli is released with the library? It's confusing.

**Comment by kasperg** [comment]
The latest version of the library is 3.1.2. It does not contain the CLI version. This is explained in [the release notes for 3.0](https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/blob/master/docs/whats-new-in-3.0.md#separation-of-library-and-console-application).

Getting a CLI version of 3.x is a work in progress as mentioned in the README for this project. I have updated references to the 2.x version so it links to the latest version of the phar file. Hopefully that will avoid confusion going forward.

**Comment by berarma** [comment]
That will certainly avoid downloading of the old version. Thanks!

So this project's code is obsolete until upgraded to work with the 3.x version of the library. From this I understand the latest stable cli is in the 2.5.5 tag of the library project. That's not to be expected but there will be some good reason.
